### PR TITLE
Use Py_UCS4 instead of deprecated Py_UNICODE

### PR DESCRIPTION
**Pull request by methane**
Fixes jamesturk/jellyfish#131.

### CODE REVIEW

**Comment by jamesturk** [comment]
thanks for this, just wanted to check if you have run the jellyfish tests locally?  (given how the cjellyfish repo is submoduled into jellyfish it is a bit tougher to have automated tests, but I can test on my end too but if you've run the tests I'll merge first and let them run in the jellyfish repo)

**Comment by methane** [comment]
I run jellyfish tests with Python 3.8 and 3.10.

By the way, I think it is better to move jellyfishmodule.c from cjellyfish to jellyfish, because it is Python specific source.

**Comment by jamesturk** [comment]
It looks like this is making tests fail on Windows

https://github.com/jamesturk/jellyfish/runs/4192091499?check_suite_focus=true

I might need to revert this for now if there isn't a quick fix as I don't have access to a Windows machine for testing.

**Comment by methane** [comment]
Ah, I forget that Py_UNICODE is UTF-16 in Windows.

I think using Py_UCS4 is better than UTF-16 for some algorithms in this library.
So I will send a pull request to fix the bug caused by UTF-16 to UCS4 transition.

**Pull request merged**
